[build]
  command = "pnpm -r --filter @aquarium/web build"
  publish = "apps/web/dist"
  functions = "apps/functions/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

